interface Citys{
    [key:string]:string
}
const citys:Citys = {
    "Beijing": "北京市",
    "Shanghai": "上海市",
    "Tianjin": "天津市",
    "Chongqing": "重庆市",
    "Akesu": "阿克苏地区",
    "Anning": "安宁市",
    "Anqing": "安庆市",
    "Anshan": "鞍山市",
    "Anshun": "安顺市",
    "Anyang": "安阳市",
    "Baicheng": "白城市",
    "Baishan": "白山市",
    "Baiyin": "白银市",
    "Bengbu": "蚌埠市",
    "Baoding": "保定市",
    "Baoji": "宝鸡市",
    "Baoshan": "保山市",
    "Bazhong": "巴中市",
    "Beihai": "北海市",
    "hechi":"河池市",
    "Benxi": "本溪市",
    "Binzhou": "滨州市",
    "Bole": "博乐市",
    "Bozhou": "亳州市",
    "Cangzhou": "沧州市",
    "Changde": "常德市",
    "Changji": "昌吉市",
    "Changshu": "常熟市",
    "Changzhou": "常州市",
    "anhui chaohu": "巢湖市",
    "Chaoyang": "朝阳市",
    "Chaozhou": "潮州市",
    "Chengde": "承德市",
    "Chengdu": "成都市",
    "Chenggu": "城固市",
    "Chenzhou": "郴州市",
    "heihe":"黑河市",
    "suihua":"绥化市",
    "Chibi": "赤壁市",
    "Chifeng": "赤峰市",
    "Chishui": "赤水市",
    "Chizhou": "池州市",
    "Chongzuo": "崇左市",
    "Chuxiong": "楚雄市",
    "DaXingAnLing":"大兴安岭地区",
    "aba":"阿坝市",
    "xingan":"兴安盟",
    "xilinguole":"锡林郭勒盟",
    "wulanchabu":"乌兰察布盟",
    "Chuzhou": "滁州市",
    "Cixi": "慈溪市",
    "Conghua": "从化市",
    "Dali": "大理市",
    "Dalian": "大连市",
    "Dandong": "丹东市",
    "yikezhao":"伊克昭盟",
    "alashan":"阿拉善盟",
    "bayinkuoleng":"巴音郭楞市",
    "bayannaoermeng":"巴彦淖尔盟",
    "shihezi":"石河子",
    "alaer":"阿拉尔",
    "Danyang": "丹阳市",
    "Daqing": "大庆市",
    "Datong": "大同市",
    "Dazhou": "达州市",
    "Deyang": "德阳市",
    "Dezhou": "德州市",
    "Dongguan": "东莞市",
    "Dongyang": "东阳市",
    "Dongying": "东营市",
    "Douyun": "都匀市",
    "Dunhua": "敦化市",
    "Eerduosi": "鄂尔多斯市",
    "Enshi": "恩施市",
    "Fangchenggang": "防城港市",
    "Feicheng": "肥城市",
    "Fenghua": "奉化市",
    "Fushun": "抚顺市",
    "Fuxin": "阜新市",
    "Fuyang": "阜阳市",
    "Fuyang1": "富阳市",
    "Fuzhou": "福州市",
    "jiangxi Fuzhou": "抚州市",
    "Ganyu": "赣榆市",
    "Ganzhou": "赣州市",
    "Gaoming": "高明市",
    "Gaoyou": "高邮市",
    "Geermu": "格尔木市",
    "Gejiu": "个旧市",
    "Gongyi": "巩义市",
    "Guangan": "广安市",
    "Guangyuan": "广元市",
    "Guangzhou": "广州市",
    "Gubaotou": "古包头市",
    "HeGang":"鹤岗市",
    "Guigang": "贵港市",
    "Guilin": "桂林市",
    "Guiyang": "贵阳市",
    "Guyuan": "固原市",
    "Haerbin": "哈尔滨市",
    "Haicheng": "海城市",
    "Haikou": "海口市",
    "Haimen": "海门市",
    "Haining": "海宁市",
    "Hami": "哈密地区",
    "Handan": "邯郸市",
    "Hangzhou": "杭州市",
    "Hanzhong": "汉中市",
    "Hebi": "鹤壁市",
    "Hefei": "合肥市",
    "Hengshui": "衡水市",
    "Hengyang": "衡阳市",
    "Hetian": "和田地区",
    "Heyuan": "河源市",
    "Heze": "菏泽市",
    "Huadou": "花都市",
    "Huaian": "淮安市",
    "Huaibei": "淮北市",
    "Huaihua": "怀化市",
    "Huainan": "淮南市",
    "Huanggang": "黄冈市",
    "Huangshan": "黄山市",
    "Huangshi": "黄石市",
    "Huhehaote": "呼和浩特市",
    "Huizhou": "惠州市",
    "Huludao": "葫芦岛市",
    "Huzhou": "湖州市",
    "Jiamusi": "佳木斯市",
    "Jian": "吉安市",
    "Jiangdou": "江都市",
    "Jiangmen": "江门市",
    "Jiangyin": "江阴市",
    "Jiaonan": "胶南市",
    "Jiaozhou": "胶州市",
    "Jiaozuo": "焦作市",
    "Jiashan": "嘉善市",
    "Jiaxing": "嘉兴市",
    "Jiexiu": "介休市",
    "Jilin": "吉林市",
    "Jimo": "即墨市",
    "Jinan": "济南市",
    "Jincheng": "晋城市",
    "Jingdezhen": "景德镇市",
    "Jinghong": "景洪市",
    "Jingjiang": "靖江市",
    "Jingmen": "荆门市",
    "Jingzhou": "荆州市",
    "Jinhua": "金华市",
    "Jining1": "集宁市",
    "Jining": "济宁市",
    "Jinjiang": "晋江市",
    "Jintan": "金坛市",
    "Jinzhong": "晋中市",
    "Jinzhou": "锦州市",
    "Jishou": "吉首市",
    "Jiujiang": "九江市",
    "Jiuquan": "酒泉市",
    "Jixi": "鸡西市",
    "Jiyuan": "济源市",
    "Jurong": "句容市",
    "Kaifeng": "开封市",
    "Kaili": "凯里市",
    "Kaiping": "开平市",
    "Kaiyuan": "开远市",
    "Kashi": "喀什地区",
    "Kelamayi": "克拉玛依市",
    "Kuerle": "库尔勒市",
    "Kuitun": "奎屯市",
    "Kunming": "昆明市",
    "Kunshan": "昆山市",
    "Laibin": "来宾市",
    "Laiwu": "莱芜市",
    "Laixi": "莱西市",
    "Laizhou": "莱州市",
    "Langfang": "廊坊市",
    "Lanzhou": "兰州市",
    "Lasa": "拉萨市",
    "Leshan": "乐山市",
    "Lianyungang": "连云港市",
    "Liaocheng": "聊城市",
    "Liaoyang": "辽阳市",
    "Liaoyuan": "辽源市",
    "Lijiang": "丽江市",
    "Linan": "临安市",
    "Lincang": "临沧市",
    "Linfen": "临汾市",
    "Lingbao": "灵宝市",
    "Linhe": "临河市",
    "Linxia": "临夏市",
    "Linyi": "临沂市",
    "Lishui": "丽水市",
    "Liuan": "六安市",
    "Liupanshui": "六盘水市",
    "Liuzhou": "柳州市",
    "Liyang": "溧阳市",
    "Longhai": "龙海市",
    "Longyan": "龙岩市",
    "Loudi": "娄底市",
    "Luohe": "漯河市",
    "Luoyang": "洛阳市",
    "Luxi": "潞西市",
    "Luzhou": "泸州市",
    "Lvliang": "吕梁市",
    "Lvshun": "旅顺市",
    "Maanshan": "马鞍山市",
    "Maoming": "茂名市",
    "Meihekou": "梅河口市",
    "Meishan": "眉山市",
    "Meizhou": "梅州市",
    "Mianxian": "勉县市",
    "Mianyang": "绵阳市",
    "Mudanjiang": "牡丹江市",
    "Nanan": "南安市",
    "Nanchang": "南昌市",
    "Nanchong": "南充",
    "Nanjing": "南京市",
    "Nanning": "南宁市",
    "Nanping": "南平市",
    "Nantong": "南通市",
    "Nanyang": "南阳市",
    "Neijiang": "内江市",
    "Ningbo": "宁波市",
    "Ningde": "宁德市",
    "Panjin": "盘锦",
    "Panzhihua": "攀枝花市",
    "Penglai": "蓬莱市",
    "Pingdingshan": "平顶山市",
    "Pingdu": "平度市",
    "Pinghu": "平湖市",
    "Pingliang": "平凉市",
    "Pingxiang": "萍乡市",
    "Pulandian": "普兰店市",
    "Puning": "普宁市",
    "Putian": "莆田市",
    "Puyang": "濮阳市",
    "Qiannan": "黔南市",
    "Qiandongnan": "黔东南市",
    "Qianxinanbuyimiaozu": "黔西南布依苗族",
    "Qidong": "启东市",
    "Qingdao": "青岛市",
    "Qingyang": "庆阳市",
    "Qingyuan": "清远市",
    "Qingzhou": "青州市",
    "Qinhuangdao": "秦皇岛市",
    "Qinzhou": "钦州市",
    "Qionghai": "琼海市",
    "Qiqihaer": "齐齐哈尔市",
    "Quanzhou": "泉州市",
    "Qujing": "曲靖市",
    "Quzhou": "衢州市",
    "Rikaze": "日喀则市",
    "Rizhao": "日照市",
    "Rongcheng": "荣成市",
    "Rugao": "如皋市",
    "Ruian": "瑞安市",
    "Rushan": "乳山市",
    "Sanmenxia": "三门峡市",
    "Sanming": "三明市",
    "Sanya": "三亚市",
    "Xiamen": "厦门市",
    "Foshan": "佛山市",
    "Shangluo": "商洛市",
    "Shangqiu": "商丘市",
    "Shangrao": "上饶市",
    "Shangyu": "上虞市",
    "Shantou": "汕头市",
    "Ankang": "安康市",
    "Shaoguan": "韶关市",
    "Shaoxing": "绍兴市",
    "Shaoyang": "邵阳市",
    "Shenyang": "沈阳市",
    "Shenzhen": "深圳市",
    "Shihezi": "石河子市",
    "Shijiazhuang": "石家庄市",
    "Shilin": "石林市",
    "Shishi": "石狮市",
    "Shiyan": "十堰市",
    "Shouguang": "寿光市",
    "Shuangyashan": "双鸭山",
    "Shuozhou": "朔州市",
    "Shuyang": "沭阳市",
    "Simao": "思茅市",
    "puer":"普洱市",
    "dehong": "德宏市",
    "nujiang": "怒江市",
    "diqing":"迪庆市",
    "honghe": "红河市",
    "wenshan": "文山市",
    "xishuangbanna":"西双版纳市",
    "Siping": "四平",
    "Songyuan": "松原市",
    "Suining": "遂宁市",
    "Suizhou": "随州市",
    "jiangsu Suzhou": "苏州市",
    "Tacheng": "塔城市",
    "Taian": "泰安市",
    "Taicang": "太仓市",
    "Taixing": "泰兴市",
    "Taiyuan": "太原市",
    "jiangsu Taizhou": "泰州市",
    "Taizhou": "台州市",
    "Tangshan": "唐山市",
    "Tengchong": "腾冲市",
    "Tengzhou": "滕州市",
    "Tianmen": "天门市",
    "Tianshui": "天水市",
    "Tieling": "铁岭市",
    "Tongchuan": "铜川市",
    "Tongliao": "通辽市",
    "Tongling": "铜陵市",
    "Tonglu": "桐庐市",
    "Tongren": "铜仁地区",
    "Tongxiang": "桐乡市",
    "Tongzhou": "通州市",
    "Tonghua": "通化市",
    "Tulufan": "吐鲁番地区",
    "Wafangdian": "瓦房店市",
    "Weifang": "潍坊市",
    "Weihai": "威海市",
    "Weinan": "渭南市",
    "Wendeng": "文登市",
    "Wenling": "温岭市",
    "Wenzhou": "温州市",
    "Wuhai": "乌海市",
    "Wuhan": "武汉市",
    "Wuhu": "芜湖市",
    "Wujiang": "吴江市",
    "Wulanhaote": "乌兰浩特市",
    "baise":"百色市",
    "wuzhishan":"五指山市",
    "wenchang":"文昌市",
    "danzhou":"儋州市",
    "wanning": "万宁市",
    "dongfang": "东方市",
    "hezhou":"贺州市",
    "dingan": "定安县",
    "chengmai": "澄迈县",
    "tunchang": "屯昌县",
    "lingao": "临高县",
    "baisha": "白沙黎族自治县",
    "changjiang": "昌江黎族自治县",
    "ledong": "乐东黎族自治县",
    "lingshui": "陵水黎族自治县",
    "baoting": "保亭黎族苗族自治县",
    "qiongzhong": "琼中黎族苗族自治县",
    "wujiaqu":"五家渠",
    "Wuwei": "武威市",
    "Wuxi": "无锡市",
    "Wuzhou": "梧州市",
    "Xian": "西安市",
    "liangshan":"凉山彝族",
    "ganzi":"甘孜藏族",
    "Xiangcheng": "项城市",
    "shennongjia":"神农架林区",
    "xiaogan":"孝感市",
    "xiangfan": "襄樊市",
    "Xianggelila": "香格里拉市",
    "tumushuke":"图木舒克",
    "boertala":"博尔塔拉市",
    "shizuishan":"石嘴山市",
    "naqu": "那曲地区",
    "changdu": "昌都地区",
    "linzhi": "林芝地区",
    "shannan": "山南地区",
    "rikaze": "日喀则地区",
    "ali": "阿里地区",
    "wuzhong":"吴忠市",
    "haidong": "海东地区",
    "haibei": "海北市",
    "hainan": "海南市",
    "huangnan": "黄南市",
    "dingxi": "定西市",
    "longnan": "陇南市",
    "linxia": "临夏市",
    "gannan": "甘南市",
    "guoluo": "果洛市",
    "yushu": "玉树市",
    "haixi": "海西市",
    "jiayuguan":"嘉峪关市",
    "jinchang":"金昌市",
    "guyuan":"固原市",
    "zhongwei":"中卫市",
    "xiangxi":"湘西市",
    "Xiangshan": "象山市",
    "Xiangtan": "湘潭市",
    "Xiangxiang": "湘乡市",
    "Xianning": "咸宁市",
    "Xiantao": "仙桃市",
    "Xianyang": "咸阳市",
    "Xicang": "西藏市",
    "Xichang": "西昌市",
    "Xingtai": "邢台市",
    "Yunfu":"云浮市",
    "jieyang":"揭阳市",
    "Xingyi": "兴义市",
    "Xining": "西宁市",
    "Xinxiang": "新乡市",
    "Xinyang": "信阳市",
    "qianjiang":"潜江市",
    "Xinyu": "新余市",
    "Xinzhou": "忻州市",
    "Suqian": "宿迁市",
    "Suyu": "宿豫市",
    "anhui Suzhou": "宿州市",
    "Xuancheng": "宣城市",
    "Xuchang": "许昌市",
    "Xuzhou": "徐州市",
    "Yaan": "雅安市",
    "Yakeshi": "牙克石市",
    "bijie":"毕节地区",
    "Yanan": "延安市",
    "Yanbian": "延边市",
    "Yancheng": "盐城市",
    "Yangjiang": "阳江市",
    "Yangquan": "阳泉市",
    "Yangzhou": "扬州市",
    "Yanji": "延吉市",
    "Yantai": "烟台市",
    "Yanzhou": "兖州市",
    "Yibin": "宜宾市",
    "Yichang": "宜昌市",
    "Yichun": "宜春市",
    "heilongjiang Yichun": "伊春市",
    "Yili": "伊犁市",
    "Yinchuan": "银川市",
    "Yingkou": "营口市",
    "Yingtan": "鹰潭市",
    "Yining": "伊宁市",
    "Yiwu": "义乌市",
    "Yixing": "宜兴市",
    "Yiyang": "益阳市",
    "Yongkang": "永康市",
    "Yongzhou": "永州市",
    "Yueyang": "岳阳市",
    "Yuhuan": "玉环市",
    "Yulin1": "榆林市",
    "Yulin": "玉林市",
    "Yuncheng": "运城市",
    "Yuxi": "玉溪市",
    "Yuyao": "余姚市",
    "Zaozhuang": "枣庄市",
    "Zengcheng": "增城市",
    "Changchun": "长春市",
    "Changhai": "长海市",
    "Zhangjiagang": "张家港市",
    "hulunbeier":"呼伦贝尔市",
    "Zhangjiajie": "张家界市",
    "Zhangjiakou": "张家口",
    "Changle": "长乐市",
    "Zhangqiu": "章丘市",
    "Changsha": "长沙市",
    "Zhangye": "张掖市",
    "Changzhi": "长治市",
    "Zhangzhou": "漳州市",
    "Zhanjiang": "湛江市",
    "Zhaodong": "肇东市",
    "Zhaoqing": "肇庆市",
    "Zhaotong": "昭通市",
    "Zhengzhou": "郑州市",
    "Zhenjiang": "镇江市",
    "Zhongshan": "中山市",
    "Zhoukou": "周口市",
    "Zhoushan": "舟山市",
    "Zhucheng": "诸城市",
    "shanwei":"汕尾市",
    "Zhuhai": "珠海市",
    "Zhuji": "诸暨市",
    "Zhumadian": "驻马店市",
    "Zhuzhou": "株洲市",
    "Zibo": "淄博市",
    "Zigong": "自贡市",
    "Zunyi": "遵义市",
    "Wulumuqi": "乌鲁木齐市",
    "Fuqing": "福清市",
    "Ezhou": "鄂州市",
    "Baotou": "包头市",
    "Xiaoshan": "萧山市",
    "Xuanhua": "宣化市",
    "Jiangyou": "江油市",
    "Ziyang": "资阳市",
    "Xinji": "辛集市",
    "Wanzhou": "万州市",
    "Zoucheng": "邹城市",
    "Shaowu": "邵武市",
    "Jiangyan": "姜堰市",
    "Xiangyin": "湘阴市",
    "Songjiang": "松江市",
    "Qitaihe": "七台河市",
    "Liling": "醴陵市",
    "Fuling": "涪陵市",
    "Gongzhuling": "公主岭市",
    "Shexian": "歙县市",
    "Xinghua": "兴化市",
    "XiangGang":"香港",
    "AoMen":"澳门",
    "TaiBei":"台北市"
}
export {citys}