export default[
    // 一线城市
    { "value": "北京" },
    { "value": "上海" },
    { "value": "广州" },
    { "value": "深圳" },

    // 新一线城市
    { "value": "成都" },
    { "value": "杭州" },
    { "value": "重庆" },
    { "value": "武汉" },
    { "value": "西安" },
    { "value": "苏州" },
    { "value": "天津" },
    { "value": "南京" },
    { "value": "长沙" },
    { "value": "郑州" },
    { "value": "东莞" },
    { "value": "青岛" },
    { "value": "沈阳" },
    { "value": "合肥" },
    { "value": "佛山" },

    // 二线城市
    { "value": "宁波" },
    { "value": "昆明" },
    { "value": "福州" },
    { "value": "济南" },
    { "value": "哈尔滨" },
    { "value": "大连" },
    { "value": "厦门" },
    { "value": "长春" },
    { "value": "温州" },
    { "value": "石家庄" },
    { "value": "南宁" },
    { "value": "南昌" },
    { "value": "贵阳" },
    { "value": "太原" },
    { "value": "乌鲁木齐" },
    { "value": "兰州" },
    { "value": "呼和浩特" },
    { "value": "海口" },
    { "value": "银川" },
    { "value": "西宁" },
    { "value": "拉萨" },

    // 三线城市
    { "value": "无锡" },
    { "value": "珠海" },
    { "value": "中山" },
    { "value": "惠州" },
    { "value": "南通" },
    { "value": "绍兴" },
    { "value": "烟台" },
    { "value": "常州" },
    { "value": "徐州" },
    { "value": "潍坊" },
    { "value": "扬州" },
    { "value": "临沂" },
    { "value": "洛阳" },
    { "value": "邯郸" },
    { "value": "芜湖" },
    { "value": "九江" },
    { "value": "宜昌" },
    { "value": "襄阳" },
    { "value": "岳阳" },
    { "value": "衡阳" },
    { "value": "遵义" },
    { "value": "赣州" },
    { "value": "汕头" },
    { "value": "湛江" },
    { "value": "柳州" },
    { "value": "绵阳" },
    { "value": "包头" },
    { "value": "大庆" },
    { "value": "鞍山" },
    { "value": "吉林" },
    { "value": "秦皇岛" },
    { "value": "威海" },
    { "value": "泰安" },
    { "value": "湖州" },
    { "value": "嘉兴" },
    { "value": "金华" },
    { "value": "盐城" },
    { "value": "镇江" },
    { "value": "泰州" },
    { "value": "台州" },
    { "value": "漳州" },
    { "value": "莆田" },
    { "value": "江门" },
    { "value": "清远" },
    { "value": "揭阳" },
    { "value": "肇庆" },
    { "value": "潮州" },
    { "value": "梅州" },
    { "value": "韶关" },
    { "value": "阳江" },
    { "value": "茂名" },
    { "value": "汕尾" },
    { "value": "河源" },
    { "value": "云浮" },

    // 特别行政区
    { "value": "香港" },
    { "value": "澳门" }
]